### ISSUE TITLE
About the Data

### ISSUE THREAD

**Issue by Leiyi-HU** [sizhelee/Diff-BGM#2]
Hey, 
Thanks for your wonderful work, but when I run the training code, I got the Error "FileNotFoundError: [Errno 2] No such file or directory: 'data/train_split_pnt/pop909_new.pickle'. I could not find the file in the urls of data that you have provided, could you provide this file?
Thanks!

**Comment by sizhelee** [comment]
Sorry for our negligence, you can find the files here. https://drive.google.com/file/d/1IK0H4_pm85oGE7Dm9DXwEKhD2G6WY6J0/view?usp=sharing

**Comment by Leiyi-HU** [comment]
Thanks for the files you provided! I found that the models.visual_encoder is not implemented in inference_sdf.py, and I wonder how to output the predictions by our own trained model and evaluate (It seems that there is no document about this evaluation pipeline in test.ipynb)?

**Comment by sizhelee** [comment]
We have just updated the 'inference_sdf.py' to solve that question. To evaluate your output, you should first use the 'inference_sdf.py' to generate midi output for the videos and then use the 'test.ipynb' and your generated midi to evaluate.
