### ISSUE TITLE
Inquiry Regarding GPU Memory and Number Requirements and Training Duration

### ISSUE THREAD

**Issue by hero-y** [sizhelee/Diff-BGM#3]
I have a few questions regarding the computational resources required to do so：

1. GPU Memory Requirement: Could you please specify the amount of GPU memory required for training the models discussed in the paper? 

2. Number of GPUs: How many GPUs are needed to achieve the results presented in the paper?

3. Training Duration: What is the approximate training time for the models using the recommended setup?

**Comment by sizhelee** [comment]
We train and test the model on a single 3090 GPU. The training process may last about one day.
